server:
  tomcat:
    threads:
      max: 600 # 최대 스레드 수
      min-spare: 64 # 최소 유지 스레드 수
    accept-count: 2000 # 대기 큐 크기
    connection-timeout: 60000 # 연결 타임아웃 (ms)

spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/spring_ignite
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: df159357
    hikari:
      maximum-pool-size: 64 # 최대 커넥션 풀 크기
      minimum-idle: 32 # 최소 유휴 커넥션 수
      idle-timeout: 300000  # 유휴 커넥션 타임아웃 (ms)
      connection-timeout: 20000  # 커넥션 타임아웃 (ms)
      max-lifetime: 1200000  # 커넥션 최대 수명 (ms)
